//https://et.wikiquote.org/wiki/Eesti_vanas%C3%B5nad
var sayings_list = [
	"Ega amet leiba küsi.",
	"Ega kott korda ei vahi, kui meest ennast juures pole.",
	"Ela sa kükakil või käpakil, ela kui tahes kehvasti oma kodus — oma päävarju all ikka parem kui teiste kõrval.",
	"Enam ruumi laias ilmas kui kitsas kehas.",
	"Enda silmas palki ei näe, teise silmas pindu küll.",
	"Ennem saab hundist hobune kui karust koduloom.",
	"Ega töö jänes ole, et eest ära jookseb.",
	"Ega töö konn ole, et eest ära hüppab.",
	"Enne mõtle, siis ütle.",
	"Ei lõppe tegija töö ja magaja uni.",
	"Hallpead austa, kulupead kummarda.",
	"Hea naine võib halvast mehest asja saada, aga hea mees halvast naisest naljalt mitte.",
	"Heal lapsel mitu nime.",
	"Hirmul on suured silmad.",
	"Hobu on loodud töötegijaks, aga mitte vaevanägijaks.",
	"Hobune ei pese ilmaski, ikke nääb, karu koa ei pese, kõik kardavad.",
	"Hommik on õhtust targem.",
	"Hulgusel kodu kõikjal.",
	"Hundid söönud, lambad terved.",
	"Igal oinal oma mihklipäev.",
	"Igal pool hea, kodus kõige parem.",
	"Igaüks taht kaua elada, keegi ei taha vanaks saada.",
	"Ilus ilmale, kuulus kõigile, kodu ei kõlba kuhugi.",
	"Inimene on kolm korda rumal: esmalt lapsepõlves, siis paari minnes ja lõpuks vanas eas.",
	"Isaga kaob pool kodu, emaga terve kodu.",
	"Isä külmä pohjatuuli, emä helejä päiväpaiste.",
	"Ika kant lõikab",
	"Jaan viskab kuuma kivi merre, Jaak jahe ja Mihkel külma.",
	"Julge hundi rind on rasvane.",
	"Jänes šampust ei joo.",
	"Jagajale jäävad näpud.",
	"Kes teisele nime annab, see ise seda kannab.",
	"Kassil saba koormaks.",
	"Kes ei tööta see ei söö!",
	"Kes kahju kardab, see kasu ei saa.",
	"Kes kassi ei toida toidab hiiri.",
	"Kes kassi kallistab, selle õue õnnistab.",
	"Kes oma last armastab, see teda ka karistab.",
	"Kes see muu koera saba kergitab kui mitte koer ise.",
	"Kes teisele auku kaevab, see ise sisse kukub.",
	"Kes viimasena naerab, naerab paremini.",
	"Kingitud hobuse suhu ei vaadata.",
	"Kinnas kotti, pöial matti.",
	"Koera keele otsas on rohi, kassi keele otsas tõbi.",
	"Kolm korda kolida on niisamma hää kui üks kord põleda.",
	"Kuidas ema nõnda tütar.",
	"Kus kiitust, seal laitust.",
	"Kured lähvad, kurjad ilmad. Haned lähvad, hallad maas. Luiged lähvad, lumi taga.",
	"Kus hulkjal penil kodu, hajapenil ase.",
	"Kus hundist räägid, seal hunt aiataga.",
	"Kus saun, seal eestlased.",
	"Kuidas küla koerale, nõnda koer külale.",
	"Kuidas külvad, nõnda lõikad.",
	"Kus suitsu seal tuld.",
	"Kes ees see mees",
	"Kõva peer on pere naer, salasitt toob sekeldusi.",
	"Küsija suu pihta ei lööda.",
	"Külaline on kaks korda armas:kui tuleb ja kui läheb.",
	"Kellel pea ei jaga, selle jagavad jalad.",
	"Käbi ei kuku kännust kaugele.",
	"Keelatud vili on magus.",
	"Kus häda kõige suurem, seal abi kõige ligem.",
	"Lapse suu seletab rohkem, kui mehe.",
	"Laida meest, mitte mehe mütsi.",
	"Lehm lüpsab suust, kana muneb nokast.",
	"Loodetuul on taevaluud.",
	"Lõoke toob lõunasooja, pääsuke päevasooja, ööbik öösooja.",
	"Lõpp hea, kõik hea.",
	"Lootus sureb viimasena.",
	"Laisa päev pikk.",
	"Maarjapäevast mees lihavaagnale ja härg heinasõimele.",
	"Magavale kassile hiir suhu ei jookse.",
	"Magusam kui mesi,tugevam kui lõvi.",
	"Meest sõnast, härga sarvest.",
	"Mets vaese mehe kasukas.",
	"Mis hiirtel viga elada kui kassi kodus põle.",
	"Mida Juku ei õpi, seda Juhan ei tea.",
	"Mida külvad,seda lõikad.",
	"Mis meelelt, see keelelt.",
	"Mis täna tehtud, see homme hooleta.",
	"Mölder elab vee ja tuulega.",
	"Mölder ja kõrtsimees põle ilmaskid ilmarahva meele järgi mette.",
	"Möldri matt ja kõrtsi mõõt olgu makstud.",
	"Mida külvad seda lõikad .",
	"Mis kasu on jooksmiseks kui oled valel teel.",
	"Mida ei saa jõuga , seda saab nõuga.",
	"Nagu ema, nõnda ka tütar.",
	"Nagu hane selga vesi.",
	"Narri meest, aga mitte mehe mütsi.",
	"Naine mehe abi, mees naise tugi.",
	"Nimi ei riku meest, kui mees ise nime ei riku.",
	"Narrid põldu ühe korra, narrib põld sind üheksa korda.",
	"Näputäis tõtt on parem kui sületäis valet.",
	"Odav kala, lahja leem.",
	"Olgu aed nii suur kui ta on, mulk ikka üks.",
	"On kolm lolli: kalamees, jahimees ja koduväimees, sest nad lähevad kodust välja ja ei tea, kas midagi saavad.",
	"Ostad hobuse, saad hoole; võtad naise, saad mure.",
	"Oma maa maasikas, võõras maa mustikas.",
	"Oma silm on kuningas.",
	"Omad koerad kisuvad, omad koerad lepivad.",
	"Oma tuba, oma luba.",
	"Paha siga, mitu viga: küll kärss kärnas, küll maa külmand.",
	"Paha siga, mitu viga: kärss kärnas, maa külmand ja ohakad torgivad.",
	"Parem kurjas kodus, kui lahkes toas.",
	"Parem pool muna kui tühi koor.",
	"Parem üks varblane pihus kui kümme tuvi katusel.",
	"Pada sõimab katelt ühed mustad mõlemad.",
	"Pill tuleb pika ilu peale",
	"Paren vaene ja tark kui rikas ja loll.",
	"Ree ja ratta surm on ikka tee pääl.",
	"Rikkast perest osta hobune, vaesest vallast võta naine.",
	"Räägi sa midagi naisele või pane plakat välja, see üsna üks.",
	"Rikkad ei räägi kunagi rahast nemad mõtlevad rahast kui pahast.",
	"Rääkimine hõbe vaikimine kuld.",
	"Raske õppustel, kerge lahingus",
	"Seni lühike võtab marja maast kui pikk kummardab.",
	"Sepapajas ja veskikojas ajatakse kõige magusamad jutud.ab suu lõ",
	"Sile kass, teravad küüned.",
	"Sõpra tuntakse hädas.",
	"Söö, mis küps, aga räägi",
	"Sõprus on väärt rohkem kui raha",
	"Terav kirves leiab kivi.",
	"Tõnisepäeval murtakse talve selg.",
	"Tänasida toimetusi ära viska homse varna.",
	"Tühi kott ei seisa püsti.",
	"Tee tööd töö ajal, aja juttu jutu ajal.",
	"Töö kardab meistrit.",
	"Töö on lolli teha.",
	"Töö on auasi.",
	"Töö on rikkuse alus.",
	"Töö inimest toidab, laiskus teda rikub.",
	"Tasa sõuad, kaugele jõuad",
	"Töö kiidab tegijat.",
	"Ussimaarjapäevast pidi uss mätast hammustama.",
	"Uhkus ajab upakile, ahnus neljakäpakile.",
	"Valel on lühikesed jalad.",
	"Varas jätab varna seina, tuli ei jäta midagi.",
	"Volbripäävast on hobuse kaeravooder metsas.",
	"Võlg on võõra oma.",
	"Vihma käest räästa alla.",
	"Vanasõnad on kuldsed sõnad .",
	"Vana tee, vana sõber.",
	"Vana hunt, kõva kont.",
	"Vana arm ei roosteta",
	"Vana arm vana karm.",
	"Õdagune uhetu om paremp ku hummugune mõstu.",
	"Õlu peab nii rammus olema, et kass võib poegadega peal istuda.",
	"Õnnetus ei hüüa tulles.",
	"Õpi palju, näe palju, ära palju pajata.",
	"Ära taha uhke olla, parem taha puhas olla.",
	"Ära hõiska enne õhtut",
	"Ööbik laulab öölaulu, kuldnokk laulab koidulaulu, lõoke laulab lõunalaulu.",
	"Ööl on üheksa poega.",
	"Üheksa ametit, kümnes nälg.",
	"Ütessä süüki anna-ai tuud hobõsõllõ tagasi, mia üte söögiga võlgu jääs.",
	"Üheksa korda mõõda, üks kord lõika.",
	"Üks loll võib rohkem küsida, kui kümme tarka vastata."
];
